apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-rvm
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
