apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2021-06-21T09:56:19Z"
  name: new-psp-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: use-unprivileged-psp
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
