apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-unprivileged-psp
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
