apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-serviceaccount
  namespace: demo

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-pod-job-admin-role
  namespace: demo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-rolebinding
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-pod-job-admin-role
subjects:
  - namespace: demo
    kind: ServiceAccount
    name: demo-serviceaccount
